name: teste-pipeline
on:
   workflow_dispatch:

jobs: 
    firtJob:
      runs-on: ubuntu-latest
      steps:
      - name: Criando pasta no linux
        run: echo "eu sou otimo" > eventos.txt
      - name: Mostrar texto
        run: cat eventos.txt
        
      
      
      
      
      
  
  
