name: teste-pipeline
on:
   workflow_dispatch:

jobs:
  contrucao-maquina: 
   runs-on: ubuntu-latest
   
   steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS_ISLEY}}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
     
    - name: 'Contrução da maquina'  
      run: gcloud storage buckets create gs://teste-bucket-v3 --project=triplox3-services-prod --default-storage-class=STANDARD --location=us-central1 --uniform-bucket-level-access

      
      
        
      
      
      
      
      
  
  
